# Generated by Django 4.1.4 on 2022-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BME280',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDcapteur', models.IntegerField()),
                ('tmp', models.FloatField()),
                ('hum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDcapteur', models.IntegerField()),
                ('btn1', models.IntegerField()),
                ('btn2', models.IntegerField()),
            ],
        ),
    ]
