# Generated by Django 4.1.4 on 2022-12-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamFinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BME280',
            new_name='BME',
        ),
    ]
