# Generated by Django 4.1.4 on 2022-12-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamFinal', '0002_rename_bme280_bme'),
    ]

    operations = [
        migrations.AddField(
            model_name='bme',
            name='IDdata',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='IDdata',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motor',
            name='btn1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='motor',
            name='btn2',
            field=models.CharField(max_length=3),
        ),
    ]
